// data.js
export const data = [
   
    {
      profile:require('./images/profile/alex krugli.jpg'),
      category: 'Animation',
      developer: 'UI/UX Boom',
      likes: 860,
      views: '10k',
      image: require('./images/animation/original-1b40103e4efe98e0b19d9256f54c6297.jpg'),
      color:'Blue',
    },
    
    {
      profile:require('./images/profile/andrey proko.jpg'),
      category: 'Branding',
      developer: 'Max',
      likes: 194,
      views: '5k',
      image: require('./images/branding/original-13ce09c81d3020b515ecf3b063422858.png'),
      color:'Orange',
    },
    {
      profile:require('./images/profile/ben kocinski.jpg'),
      category: 'Illustration',
      developer: 'Emote Studio',
      likes: 89,
      views: '4.8k',
      image: require('./images/illustration/original-0c202c998fd52e383f761d62bc6acdc1.jpg'),
      color:'Blue',
    },
    {
      profile:require('./images/profile/ben.jpg'),
      category: 'Mobile',
      developer: 'Mark WorkLab',
      likes: 94,
      views: '3k',
      image: require('./images/mobile/original-0f71d935c1a1ec4d64bd96c43d850dfb.png'),
      color:'Black',
    },
    {
      profile:require('./images/profile/coric design.jpg'),
      category: 'Print',
      developer: 'Ronas Studio',
      likes: 78 ,
      views: '5.8k',
      image: require('./images/print/original-0c4da3dbae1afd8ef0b20b95b85c47e7.png'),
      color:'Orange',

    },
    {
      profile:require('./images/profile/darya seme.png'),
      category: 'Product Design',
      developer: 'Dipa Inhouse',
      likes: 58,
      views: '45',
      image: require('./images/webdes/original-ed3419df5400511cd1be200be1066bce.png'),
      color:'White',
    },
    {
      profile:require('./images/profile/demian orella.png'),
      category: 'Typography',
      developer: 'Lalit',
      likes: 99,
      views: '300',
      image: require('./images/print/original-ca71dc36ef342d01396f5a7af5e0e60f.jpg'),
      color:'Purple',

    },
    {
      profile:require('./images/profile/DKNG.png'),
      category: 'Web Design',
      developer: 'Kevin Studio',
      likes: 44,
      views: '5k',
      image: require('./images/webdes/original-0a7ebbc6ed107723bb963bdebdccca4b.png'),
      color:'Purple',
    },



    // Add more image data...

    {
      profile:require('./images/profile/dstudio.png'),
      category: 'Web Design',
      developer: 'Roans',
      likes: 70,
      views: '7k',
      image: require('./images/webdes/original-0a47b717aa3b56bb8ccddcfa89c7fd18.png'),
      color:'Purple',
    },
    {
      profile:require('./images/profile/focaus lab.png'),
      category: 'Web Design',
      developer: 'Bang Bang',
      likes: 87,
      views: '6.2k',
      image: require('./images/webdes/original-2c5e8a0a9a07dbaab9b8a70bbeb1ccf7.png'),
      color:'Black',
    },
    {
      profile:require('./images/profile/lisa.jpg'),
      category: 'Web Design',
      developer: 'Brandon',
      likes: 57,
      views: '2k',
      image: require('./images/webdes/original-9cb5e36a9f7ed7e8faafc03fa713ebac.png'),
      color:'Green',
    },
    {
      profile:require('./images/profile/makers.png'),
      category: 'Web Design',
      developer: 'Folio',
      likes: 302,
      views: '9.1k',
      image: require('./images/webdes/original-31f070e7b0a0c553b60a507f032f2bcc.png'),
      color:'Orange',
    },
    {
      profile:require('./images/profile/mohamed.jpg'),
      category: 'Web Design',
      developer: 'Zajno',
      likes: 109,
      views: '8.8k',
      image: require('./images/webdes/original-68d2bbcffc956d7028ebfc27d0c5d283 (1).png'),
      color:'Orange',
    },


    {
      profile:require('./images/profile/nice.jpg'),
      category: 'Print',
      developer: 'Poja kicks',
      likes: 69,
      views: '5k',
      image: require('./images/print/original-1d16603679e4a973e967afea3e266644.jpg'),
      color:'Orange',
    },
    {
      profile:require('./images/profile/pavlov visuals.jpg'),
      category: 'Print',
      developer: 'Nino Studio',
      likes: 90,
      views: '3k',
      image: require('./images/print/original-11b3617e51ae0de618bd3b8d4f5ff0e1.png'),
      color:'Green',
    },
    {
      profile:require('./images/profile/peter vorth.png'),
      category: 'Print',
      developer: 'Andrii',
      likes: 14,
      views: '22',
      image: require('./images/print/original-17fe7d707507d5ee040481f4c436e9f0.png'),
      color:'Black',
    },
    {
      profile:require('./images/profile/ranganath kri.png'),
      category: 'Print',
      developer: 'Arts Ohla ',
      likes: 94,
      views: '5.8k',
      image: require('./images/print/original-86eab816cb5e2d09b72ac137f4d89cb6.jpg'),
      color:'Blue',
    },
    {
      profile:require('./images/profile/sebastiaan.jpg'),
      category: 'Print',
      developer: 'Joe on',
      likes: 94,
      views: '382',
      image: require('./images/print/original-405e7f4fe2d3be6c30829ad7e35808b6.jpg'),
      color:'Green',
    },



    //animation
    {
      profile:require('./images/profile/siege media.jpg'),
      category: 'Animation',
      developer: 'Halo Lab',
      likes: 266,
      views: '9.4k',
      image: require('./images/animation/original-0d584d6b2e608db5d1a7dce0c9f1545f.png'),
      color:'Pink',
    },
    {
      profile:require('./images/profile/skilline Desig.jpg'),
      category: 'Animation',
      developer: 'TubTik',
      likes: 26,
      views: '89',
      image: require('./images/animation/original-5db073689131dfb8e6a0449ca3b8bcee.png'),
      color:'Purple',
    },
    {
      profile:require('./images/profile/tubik.jpg'),
      category: 'Animation',
      developer: 'Coric Design',
      likes: 76,
      views: '400',
      image: require('./images/animation/original-9b99e7bf4db175ac290d585279c0dc2d.jpg'),
      color:'Yellow',
    },
    {
      profile:require('./images/profile/1.jpg'),
      category: 'Animation',
      developer: 'Alddddo',
      likes: 10,
      views: '48',
      image: require('./images/animation/original-46d809624bd9508c9357947476cf3080.png'),
      color:'Blue',
    },
    {
      profile:require('./images/profile/2.jpg'),
      category: 'Animation',
      developer: 'Brightcount',
      likes: 4,
      views: '9',
      image: require('./images/animation/original-69aef47a82e56888d1ef2e88e84ceef1.png'),
      color:'Green',
    },
    {
      profile:require('./images/profile/3.jpg'),
      category: 'Animation',
      developer: 'DanLabs',
      likes: 26,
      views: '98',
      image: require('./images/animation/original-830107f852ff4b5730b97eab445f9276.jpg'),
      color:'Red',
    },
    {
      profile:require('./images/profile/4.jpg'),
      category: 'Animation',
      developer: 'Joe Gold',
      likes: 79,
      views: '2k',
      image: require('./images/animation/original-b25782973b9036b064bd5f4635f8c0cc.jpg'),
      color:'Yellow',
    },


    //branding
    {
      profile:require('./images/profile/5.jpg'),
      category: 'Branding',
      developer: 'Pickolab',
      likes: 94,
      views: '2k',
      image: require('./images/branding/original-9daf4648664941c86fd35a9ea83da630.png'),
      color:'Green',
    },
    {
      profile:require('./images/profile/6.jpg'),
      category: 'Branding',
      developer: 'Charles',
      likes: 560,
      views: '8k',
      image: require('./images/branding/original-70aaddd8113d610b4c97fa0f310721ff.png'),
      color:'Green',
    },
   
    {
      profile:require('./images/profile/7.jpg'),
      category: 'Branding',
      developer: 'Lando',
      likes: 134,
      views: '2k',
      image: require('./images/branding/original-c0ecde709defdc4bc04eef7c864c1647.png'),
      color:'Red',
    },
    {
      profile:require('./images/profile/8.jpg'),
      category: 'Branding',
      developer: 'Carlos Sainz',
      likes: 820,
      views: '8k',
      image: require('./images/branding/still-4ca2d495f92d954be531d416759d9d6e.png'),
      color:'White',
    },
    {
      profile:require('./images/profile/9.jpg'),
      category: 'Branding',
      developer: 'Hamilton',
      likes: '7',
      views: '1k',
      image: require('./images/branding/still-617816e01368facdfd3e84a310f9c4d9.png'),
      color:'Purple',
    },
    {
      profile:require('./images/profile/10.jpg'),
      category: 'Branding',
      developer: 'Russell',
      likes: 94,
      views: '3k',
      image: require('./images/branding/still-e41458019a63cfaab388fd90fcad3726.png'),
      color:'Blue',
    },

    {
      profile:require('./images/profile/11.jpg'),
      category: 'Illustration',
      developer: 'Fernano',
      likes: 34,
      views: '59',
      image: require('./images/illustration/original-03fbe0280f793f82c05d07605e3f0078.jpg'),
      color:'Red',
    },
    {
      profile:require('./images/profile/12.jpg'),
      category: 'Illustration',
      developer: 'Yuki',
      likes: 94,
      views: '2.8k',
      image: require('./images/illustration/original-7e507a7f5a24641bf6780411e772104b.png'),
      color:'Pink',
    },
    {
      profile:require('./images/profile/13.jpg'),
      category: 'Illustration',
      developer: 'Ricciardo',
      likes: 9,
      views: '89',
      image: require('./images/illustration/original-41d4a228435284e8cdeadb87f4c388fa.png'),
      color:'White',
    },
    {
      profile:require('./images/profile/14.jpg'),
      category: 'Illustration',
      developer: 'Oliver Bearman',
      likes: 194,
      views: '500',
      image: require('./images/illustration/original-11167ea6cc2376c71931b1f85fd528bc.png'),
      color:'Yellow',
    },
    {
      profile:require('./images/profile/15.jpg'),
      category: 'Typography',
      developer: 'Nico Studio',
      likes: 38,
      views: '55',
      image: require('./images/illustration/original-93772be13f7d3f77f5ffa77cf75a8c33.png'),
      color:'Orange',
    },
    {
      profile:require('./images/profile/16.jpg'),
      category: 'Typography',
      developer: 'Gasly',
      likes: 914,
      views: '4.8k',
      image: require('./images/illustration/original-ec5f536db40ce66f4be851e2e6d92c6c.png'),
      color:'Red',
    },

    {
      profile:require('./images/profile/17.jpg'),
      category: 'Typography',
      developer: 'Albon Will',
      likes: 914,
      views: '1k',
      image: require('./images/illustration/still-9cb57277e924737b21a95aebc831d0fc.png'),
      color:'Blue',
    },

    {
      profile:require('./images/profile/18.jpg'),
      category: 'Mobile',
      developer: 'Sheldon',
      likes: 99,
      views: '5k',
      image: require('./images/mobile/original-4c2375a535c27b7c6ac8bfcb7185daf1.png'),
      color:'Blue',
    },

    {
      profile:require('./images/profile/19.jpg'),
      category: 'Mobile',
      developer: 'Amy Drake',
      likes: 90,
      views: '5k',
      image: require('./images/mobile/original-092c7802ca5e33953a853a53ebc3e1b2.png'),
      color:'White',
    },

    {
      profile:require('./images/profile/20.jpg'),
      category: 'Mobile',
      developer: 'Zero Dip',
      likes: 65,
      views: '89',
      image: require('./images/mobile/original-0297a4d57402c3d9393ff6df8784499c.png'),
      color:'Green',
    },
    {
      profile:require('./images/profile/21.jpg'),
      category: 'Mobile',
      developer: 'Hugbag Hans',
      likes: 51,
      views: '90',
      image: require('./images/mobile/original-5758f7774942b19f0cace201c9e48447.png'),
      color:'Purple',
    },
    {
      profile:require('./images/profile/22.jpg'),
      category: 'Product Design',
      developer: 'Penn',
      likes: 560,
      views: '6k',
      image: require('./images/mobile/still-841c868b2d6441a3a4079de03c0c2348.png'),
      color:'Blue',
    },
    {
      profile:require('./images/profile/23.jpg'),
      category: 'Product Design',
      developer: 'Dom Go',
      likes: 940,
      views: '5k',
      image: require('./images/mobile/original-d3cf2fece3675106b38c07eaac760e9b.png'),
      color:'Yellow',
    },
    {
      profile:require('./images/profile/24.jpg'),
      category: 'Product Design',
      developer: 'Raj Labs',
      likes: 674,
      views: '1k',
      image: require('./images/mobile/original-ac8b704ea24fb3f66d9b604d1156cf93.png'),
      color:'Purple',
    },
  ];
  
  export const getCategories = () => {
    const categories = new Set(data.map(item => item.category));
    return Array.from(categories);
  };
  